Feature/StoryLog 이전 대화 내용 기록 기능 추가
pknu-wap/2024-1-Game-2-Team pull request #120
Opened 2024-07-09 13:46 UTC by Kkumteulyi

## 개요

스토리 진행 도중에 나왔던 대사들을 확인할 수 있는 기능을 추가하였습니다.

## 변경 사항

### 이전 대화 내용 기록 
- 최대 10개의 대화를 기록하는 UI와 패널을 열 수 있는 버튼을 추가하였습니다
- 가장 최근에 추가된 대화부터 아래에서 위로 쌓여가는 방식으로 구현되어 있습니다
- 기록된 대화가 10개를 넘길 경우 가장 마지막 대화부터 삭제됩니다

### 함수
**ToggleObject**
- 대화 기록 패널을 버튼 클릭에 따라 토글 형태로 온/오프 하는 함수입니다.

**AddLog**
- DialogueManager에서 이름과 대화 내용을 가져와 각각의 컴포넌트에 할당하는 함수입니다.
- 프리팹 오브젝트들에서 GetChild를 사용하여 이름, 대화 내용 오브젝트에 접근 후, GetComponent를 통해 TMP_Text에 할당합니다.
- 리스트에 저장된 개수가 10개를 넘길 경우 가장 오래된 대화부터 삭제되도록 RemoveAt(0)를 사용하였습니다.

## 참고 자료

자식 오브젝트의 컴포넌트 가져오기 - https://learnandcreate.tistory.com/2210
동일한 태그를 가진 오브젝트를 배열로 만들기 - https://curioso365.tistory.com/106

2024-07-16 16:31 UTC, miniron-v requested changes
회의 때 나왔던 부분들 수정된 후에 재검토하겠습니다.

2024-07-27 07:48 UTC, Kkumteulyi commented
위의 2가지 사항 수정하였습니다.

2024-07-27 12:32 UTC, miniron-v approved these changes

2024-07-27 12:33 UTC, miniron-v commented
스토리 배속은 클릭이 안 돼 확인할 수 없었으나 로그는 잘 되네요. 로그 배경 색, 이벤트 넘김 효과까지 확인되면 바로 머지하겠습니다

2024-07-27 13:28 UTC, merged