이벤트 데이터 딜레이 구현
pknu-wap/2024-1-Game-2-Team pull request #123
Opened 2024-07-12 14:06 UTC by ThisIsTAEWON

## 개요

이벤트 데이터 객체가 딜레이 만큼 지연된 후에 리스트에 삽입됩니다.

## 변경 사항

이벤트 데이터 객체가 딜레이 변수를 가집니다.
DialogueManager 스크립트에 딜레이가 있는 이벤트 객체를 저장하는 delayDictionary 자료구조를 구현했습니다.
딜레이가 있는 addEvent는 이제 실행 대기 리스트가 아닌 delayDictionary에 추가됩니다.
랜덤한 이벤트를 선택할 때마다 모든 딜레이는 1씩 감소하며 딜레이가 0이된 이벤트 데이터 객체는 실행 대기 리스트에 추가됩니다.

## 참고 자료

2024-07-16 03:38 UTC, miniron-v requested changes

2024-07-16 03:38 UTC, miniron-v commented on Assets/02. Scripts/Story/Managers/DialogueManager.cs
> +                        }
사실 생각해보면, 둘을 구분하지 않고 delayEvent에 삽입한다면? delay를 1씩 줄이는 과정에서 자연스럽게 추가가 됩니다.

delayEvent를 거치지 않는단 점에서 효율적이기 때문에 제가 적은 방법이 더 낫다는 건 아니지만, 로직을 더 간결하게 짤 수 있다! 정도만 짚어드리고 싶었어요.

2024-07-16 03:38 UTC, miniron-v commented on Assets/02. Scripts/Story/Managers/DialogueManager.cs
> +            }
완벽합니다! 제가 짰더라도 크게 달라지지 않았을 것 같네요. 실력이 많이 는 것 같아서 뿌듯합니다... ㅎㅎ

전 구조체와 priority queue를 쓰는 방법을 떠올렸었는데, Dictionary를 쓰면 확실히 구조체를 쓰지 않게 되니 편리하네요.

다만, 이 로직대로라면 딜레이가 3일 경우 **4턴 지난 후** 추가될 것으로 예상되는데, 이 부분 어떤지 확인해주시면 좋을 것 같습니다. (0이 된 후 한 턴 기다려야 검사함)

2024-07-16 04:46 UTC, ThisIsTAEWON commented
수정 완료했습니다

2024-07-17 07:11 UTC, tgyuuAn commented
아니 이 사람들 계속 개발하고있짢아 ...?

어메이징....

2024-07-19 16:31 UTC, miniron-v approved these changes
베리 굿입니당 고생하셨어요

2024-07-19 16:31 UTC, merged