로컬 세이브
pknu-wap/2024-1-Game-2-Team pull request #142
Opened 2024-08-14 14:20 UTC by ThisIsTAEWON

## 개요

게임을 저장하고 불러오는 로컬 세이브 기능을 개발합니다.

## 변경 사항

### Data
- C#에서 Dictionary의 직렬화를 지원하지 않아 DelayDictionary의 저장 방식을 변경합니다.
- key와 value를 필드로 갖는 DictionaryData 클래스를 선언해 Dictionary를 DictionaryData의 리스트로 변환하여 관리합니다.

### DataManager
#### StartSavedGame
- 데이터를 로드하고 각 위치에 삽입합니다.
- 이벤트 씬으로 전환하고 불러온 이벤트를 진행합니다.
#### DictionaryToDictionaryData
- Dictionary를 DictionaryData의 리스트 형으로 변환해 반환합니다.
#### DictionaryDataToDictionary
- DictionaryData를 Dictionary의 리스트 형으로 변환해 반환합니다.

### DialogueManager
- 이벤트가 시작할 때, 현재 이벤트가 Relation 이벤트가 아니라면 데이터를 저장합니다.
- SaveData가 SaveDialogueData로 변경되었습니다.
- LoadData가 LoadDialogueData로 변경되었습니다.
- DelayDictionary가 DictionaryData의 리스트형으로 변환되어 세이브/로드 됩니다.
#### ProcessLoadedEvent
- 저장된 게임을 불러와 진행한 후, 불러온 currentEvent가 종료되면 ProcessRandomEvent를 호출합니다.
- DataManager의 StartSavedGame 함수의 일부를 코루틴으로 사용하기 위해 분리해서 DialogueManager에서 관리합니다.

### SoundManager
- 이제 싱글톤으로 관리합니다.
- 사운드 설정을 변경할 때마다 로컬 데이터로 저장합니다.

### ResolutionManager
- 이제 싱글톤으로 관리합니다.
- 해상도 설정을 변경할 때마다 로컬 데이터로 저장합니다.

### Player
#### SaveHp
- Hp를 Data 객체에 저장합니다
#### LoadHp
- Data 객체에서 Hp를 불러옵니다.

## 참고 자료

2024-08-15 03:44 UTC, miniron-v approved these changes

2024-08-15 17:01 UTC, miniron-v requested changes
Relation 이벤트 때도 세이브를 저장한다면 **선택지를 고른 후, 맘에 안 들면 껐다 키며 다시 선택하는** 악용을 막을 수 있을 것 같은데, 어떤가요?

2024-08-17 09:19 UTC, ThisIsTAEWON commented
> Relation 이벤트 때도 세이브를 저장한다면 **선택지를 고른 후, 맘에 안 들면 껐다 키며 다시 선택하는** 악용을 막을 수 있을 것 같은데, 어떤가요?

그럼 유저가 게임을 불러왔을 때 Relation 이벤트를 먼저 봐야하는 데 이전 맥락/로그가 없으니 어색하지 않을까요? 저희 게임이 오프라인이고 스코어를 내지 않기 때문에 경험을 선택하는 건 유저에게 맡겨도 된다고 생각합니다. 선택지에 항상 명확한 우열이 있지도 않구요.

2024-08-21 08:28 UTC, miniron-v commented
> > Relation 이벤트 때도 세이브를 저장한다면 **선택지를 고른 후, 맘에 안 들면 껐다 키며 다시 선택하는** 악용을 막을 수 있을 것 같은데, 어떤가요?
> 
> 그럼 유저가 게임을 불러왔을 때 Relation 이벤트를 먼저 봐야하는 데 이전 맥락/로그가 없으니 어색하지 않을까요? 저희 게임이 오프라인이고 스코어를 내지 않기 때문에 경험을 선택하는 건 유저에게 맡겨도 된다고 생각합니다. 선택지에 항상 명확한 우열이 있지도 않구요.

플레이어가 **불러오기**를 선택한 시점엔, 오랜 시간이 지났더라도 "아, 내가 하다가 껐구나."라는 생각이 들어 시작 대사는 맥락이 어색하지 않았습니다.

오히려 선택지를 이것저것 다 눌러볼 수 있는 게임은 **완성도가 떨어지는 게임** 느낌이 나서 유저들 사이에서 평가가 많이 내려갈 거 같아요.

이거 관련해선 회의 때 다뤄봅시다

2024-08-22 14:03 UTC, miniron-v approved these changes
정말 고생 많으셨습니다!

2024-08-22 14:03 UTC, merged